name: Feature Request
description: Suggest an idea for the app.
title: '[Feature Request]: '
labels:
  - enhancement
body:
  - type: checkboxes
    id: '1'
    attributes:
      label: Preflight checklist
      description: Make sure you completed this before creating an issue.
      options:
        - label: >-
            I have searched the [issue
            tracker](https://github.com/kainatquaderee/miku/issues) for a bug report
            that matches the one I want to file, without success.
          required: true
        - label: >-
            I have searched the [features
            list](https://github.com/kainatquaderee/miku#features) for this feature,
            and I couldn't find it.
          required: true
        - label: >-
            I have checked that I'm using the [latest
            stable](https://github.com/kainatquaderee/miku/releases/latest) version
            of the app.
          required: true
  - type: textarea
    id: '4'
    attributes:
      label: Problem Description
      description: >-
        Please add a clear and concise description of the problem you are
        seeking to solve with this feature request.
    validations:
      required: true
  - type: textarea
    id: '5'
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like in a clear and concise manner.
    validations:
      required: true
